name: clear old events

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/run-jar.yml
    with:
      task: REMOVE_OLD_EVENTS
    secrets: inherit
