name: clear mobile cameras

on:
  schedule:
    - cron:  '0 17 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/run-jar.yml
    with:
      task: CLEAR_MOBILE_CAMERAS
    secrets: inherit
