name: clear mobile cameras

on:
  schedule:
    - cron:  '0 17 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add nested repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPO_PATH }} 
          token: ${{ secrets.REPO_TOKEN }} 
   
      - name: set up JDK 171
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: clear cameras
        run:
          java -Xms128m -Xmx4g -jar jar/grodno-roads-github-actions.jar CLEAR_MOBILE_CAMERAS
