name: clear old events

on:
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add nested repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPO_PATH }} 
          token: ${{ secrets.REPO_TOKEN }} 

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: clear old events
        run:
          java -Xms128m -Xmx4g -jar jar/grodno-roads-github-actions.jar REMOVE_OLD_EVENTS
