name: fetch mobile cameras

on:
  schedule:
    - cron:  '0 3-7 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/run-jar.yml
    with:
      task: FETCH_NEW_CAMERAS
    secrets: inherit
