name: Prevent Workflows from being disabled

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
 
jobs:
  cronjob-based-github-action:
    name: Cronjob based github action
    permissions:
        actions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Keep Alive Workflow
        uses: gautamkrishnar/keepalive-workflow@v2
        with:
          committer_username: ${{ github.repository_owner }}
          committer_email: "egorikftp@gmail.com"
          time_elapsed: 1
