name: fetch users online

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:
    uses: ./.github/workflows/run-jar.yml
    with:
      task: USERS_ONLINE
      google_credentials_env: true
    secrets: inherit
